# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BmNR1cL6/FwdZO0TVSMMojiKRMJjnmfNPriwW44GVJUEAS9ZZK84sUCYijAM+Y4msuJnehqe65qaT6BC08GChP+GHGXvD1LBWir509ejrcMRE3J3GqXrCOJcGb1LeIT5RDODzwKv6A3umyJmd39oEdBchu+hupfe76rGZu0tsjWc+6VVHRDV+jZHdxcnI+Dk5+rB4i++g3gJhH3ezy2RyuoCc/psa1k7aLl46GaiqH9waG5kOUK90hTSwKN5IBmELMnF6KhDhMp7sGjGv0B6ZiymvvgWMpKASzlw+OuR0kbTyPDPz3+nxrw8Sy6jIwix7Na/GcfeydU4F2ivo0oJjIpCvwgao5hZSdDWRZ8evPGzFrsVtxYh759zaNYKiTVOpSFdlQJ8dEbrCclQ+RLR1NbhGgdwzC5/4OfZzZieerzf/JKw30zzbqb8MnsuKIekMnR61on4hIfiy96jgZ/rpLZ65QDiJ0EzKdEZ2rak7QNBUkdcXpx+e4Bn4HECHCj9apsmq25604bsOF8qQmhkan611u4Bm6Sv80UzC4s62qwee6U8T3xwhdO8TRBFeV3VN9ES11F+ZPE0oX0aVHj1zKOPWyFOIRZaMfs20JLZjKJOzFLtHz4J6RQ594VexMJO9df3+Mhq1e4eEAjV1Johk53wYyhNyjv/tD7/qHtxbn8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
