# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SKuaW/OLRrhk8CF8iQQ6sDundv5fbGSEUeIZArlL3p4joorwIVrI57FIYZNB23+T7OKZ83yn67eolqkDZlqPVSStAjdkKeTQRRuFaktCMV3fXFGdr8BIOvefmf+hBcNNk9TQa1DjkI2hVZr412gZKccj2BcXfQTsXbWqgHeBq/8it9IOaBDAjcxg6a7KtH8CfeMCViDotwAyNiv5MmaFPzaWXcHxAb/wqN7/W1/SAZqfldlZv3QUB5R1s+Yl0bJ0QwqlMho0AV0WfQe50wsrsnErawaqO0yHQp2gRj+gdjSWL1+f4hnqbO7wUi0ei+1pac+46LiLDIwNUVq1ztG5QazkVc2uYBM5ZOXSrFApOoXrKu6GOW0x3lqZqJEp4FlSGRPpsAn/9+y1gXsg9bgrJB01OAB0c4zRPmFQfWC3P+e6n3mTx27WL/82Fkwbg/u9NdImiRg26FiQSuShEsRyTU5I53JVQQi8YHiHFWFqw2rNCyZ0n8gzhjuRyR6ezSzHXyAo2ePweVDdwvGeaceJeClTElK1dwo6rqkPKGr9KQWNpZyX0SoxrnVwGFC6NoLcikR0wsPtzmXaItt9GSwyljJdS5R5nhAVvb5OTYtRaLXhMI0kQmqXB8jxqWeWdvTNBJuRKxV8FkiYaaQQoiU0v0Pq1WyBeeiIhcZKwc/o0Qk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
