travis:
  secure:
    BINSTAR_TOKEN: SKuaW/OLRrhk8CF8iQQ6sDundv5fbGSEUeIZArlL3p4joorwIVrI57FIYZNB23+T7OKZ83yn67eolqkDZlqPVSStAjdkKeTQRRuFaktCMV3fXFGdr8BIOvefmf+hBcNNk9TQa1DjkI2hVZr412gZKccj2BcXfQTsXbWqgHeBq/8it9IOaBDAjcxg6a7KtH8CfeMCViDotwAyNiv5MmaFPzaWXcHxAb/wqN7/W1/SAZqfldlZv3QUB5R1s+Yl0bJ0QwqlMho0AV0WfQe50wsrsnErawaqO0yHQp2gRj+gdjSWL1+f4hnqbO7wUi0ei+1pac+46LiLDIwNUVq1ztG5QazkVc2uYBM5ZOXSrFApOoXrKu6GOW0x3lqZqJEp4FlSGRPpsAn/9+y1gXsg9bgrJB01OAB0c4zRPmFQfWC3P+e6n3mTx27WL/82Fkwbg/u9NdImiRg26FiQSuShEsRyTU5I53JVQQi8YHiHFWFqw2rNCyZ0n8gzhjuRyR6ezSzHXyAo2ePweVDdwvGeaceJeClTElK1dwo6rqkPKGr9KQWNpZyX0SoxrnVwGFC6NoLcikR0wsPtzmXaItt9GSwyljJdS5R5nhAVvb5OTYtRaLXhMI0kQmqXB8jxqWeWdvTNBJuRKxV8FkiYaaQQoiU0v0Pq1WyBeeiIhcZKwc/o0Qk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
